# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
chache: packages

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - libtiff-dev
      - libpng-dev
      - libjpeg-dev
      - libfftw3-dev