# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: true
chache: packages

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - libtiff-dev
      - libpng-dev
      - libjpeg-dev
      - libfftw3-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - tesseract-ocr-fra
      - libpoppler-cpp-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
